apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-prod
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-stage
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-test
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
  annotations:
    argocd.argoproj.io/sync: "true"
