apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-prod
  labels:
    argocd.argoproj.io/managed-by: spider-cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-stage
  labels:
    argocd.argoproj.io/managed-by: spider-cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-test
  labels:
    argocd.argoproj.io/managed-by: spider-cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: aaa-application-cicd
  annotations:
    argocd.argoproj.io/sync: "true"