apiVersion: v1
kind: ResourceQuota
metadata:
 name: aaa-application-prod-quota
 namespace: aaa-application-prod
spec:
 hard:
   pods: '8'
   requests.cpu: '2'
   requests.memory: 4Gi
   limits.cpu: '8'
   limits.memory: 10Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: aaa-application-stage-quota
 namespace: aaa-application-stage
spec:
 hard:
   pods: '5'
   requests.cpu: '2'
   requests.memory: 2Gi
   limits.cpu: '8'
   limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: aaa-application-test-quota
 namespace: aaa-application-test
spec:
 hard:
   pods: '5'
   requests.cpu: '2'
   requests.memory: 2Gi
   limits.cpu: '8'
   limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: aaa-application-cicd-quota
 namespace: aaa-application-cicd
spec:
 hard:
   pods: '6'
   requests.cpu: '4'
   requests.memory: 4Gi
   limits.cpu: '10'
   limits.memory: 12Gi