kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-access
  namespace: aaa-application-cicd
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-access
  namespace: aaa-application-prod
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-access
  namespace: aaa-application-stage
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: app-access
  namespace: spider-test
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: app-admins
users:
  - opentlc-mgr