kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aaa-application-prod-image-pull
  namespace: aaa-appplication-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: default
  namespace: aaatest
---
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: aaa-application-stage-image-pull
    namespace: aaa-appplication-stage
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: aaatest
---
  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: aaa-application-test-image-pull
    namespace: aaa-appplication-test
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: aaatest